config/routes.rb
CodePal::Application.routes.draw do
  resources :users
  resources :projects do
    member do
      get 'workspace', to: 'projects#workspace', as: 'workspace' 
      get 'workspace/session', to: 'projects#workspace_session', as: 'workspace_session'
      
      get 'members/new', to: 'project_members#new', as: 'new_members'
      get 'members', to: 'project_members#index', as: 'members'
      post 'members', to: 'project_members#create', as: 'members'
      # resources :project_members, only: [:index, :new]
    end

    resources :users, only: [] do
      member do
        delete 'membership', to: 'project_members#destroy', as: 'members'
      end
    end
  end

  namespace :api do
    resources :projects, only: [:show] do
      resources :project_files, only: [:index] do
        collection do
          post 'save', to: 'project_files#save', as: 'save'
        end
      end
    end

    resources :user, only: [:show] do
      resources :projects, only: [:index]
    end
  end

  root to: 'projects#index'

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy', as: 'logout'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :creator_id, :description, :title

  validates :creator_id, presence: true
  validates :description, presence: true
  validates :title, presence: true

  has_many :project_files

  belongs_to(
    :creator,
    class_name: "User",
    foreign_key: :creator_id,
    primary_key: :id
  )

  has_many(
    :project_memberships,
    class_name: "ProjectMember",
    foreign_key: :project_id,
    primary_key: :id
  )

  has_many :members, through: :project_memberships, source: :user
  
  @file_types = %w(html css js)
  
  @file_types.each do |file_type|
    define_method file_type do
      self.project_files.select { |file| file.file_type == file_type) }.first
    end
  end
  
  after_create do
    @file_types.each do |type|
      ProjectFile.create!(file_type: type, body: "", project_id: self.id)
    end
  end
  
  def all_members
    [self.creator] + self.members
  end

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  def index
    @projects = User.find(params[:user_id]).created_projects

    render json: @projects
  end

  def show
    @project = Project.find(params[:id])

    render json: @project
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper

  before_filter :require_logged_in!, only: [:new, :create, :edit, :update, :destroy, :workspace_session]
  before_filter :require_creator!, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all

    render :index
  end

  def new
    @project = Project.new

    render :new
  end

  def create
    @project = Project.new(params[:project])

    @project.creator_id = current_user.id

    if @project.save
      redirect_to workspace_project_url(@project.id)
    else
      add_flash(:errors, @project.errors.full_messages)
      redirect_to new_project_url
    end
  end

  def show
    @project = Project.find(params[:id])

    render :show, layout: false
  end

  def edit
    @project = Project.find(params[:id])

    render :edit
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to project_url(@project.id)
    else
      add_flash(:errors, @project.errors.full_messages)
      redirect_to edit_user_url
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_url
  end

  def workspace
    render :workspace
  end

  def workspace_session
    render :workspace_session 
  end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def require_creator!
    redirect_to root_url unless Project.find(params[:id]).creator_id == current_user.id
  end
end

app/views/projects/_editor.html.erb
<div class="fadein scaleInv anim_<%= anim %> <%= direction %> editor-container" id="<%= type %>-container">
  <div class="editor-options">
    <% options.each do |option| %>
      <button type="button"><%= option %></button>
    <% end %>
  </div>
  <div class="editor-header" data-type="<%= type %>">
    <button type="button" class="gear-button">
      <%= image_tag "gear.png", class: "gear" %>
    </button>

    <span><%= type.upcase %></span>

    <input class="editor-checkbox" type="checkbox" checked>
  </div>

  <div class="editor" id="<%= type %>-box"></div>
</div>

app/views/projects/_form.html.erb
<form action="<%= url %>" method="post" class="create-project">
  <% if edit %>
  <input type="hidden" name="_method" value="PUT">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="project-title">Title:</label><br>
  <input type="text" name="project[title]" value="<%= @project.title %>" id="project-title" placeholder="title"><br><br>

  <label for="project-description">Description:</label><br>
  <textarea cols=50 rows=10 name="project[description]" id="project-description" placeholder="description"><%= @project.description %></textarea><br><br>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/projects/_show_projects.html.erb
<% first_row = true %>

<ul class="projects-list">
<% projects.each_with_index do |project, index| %>
  <% if index % 3 == 0 %>
    <% unless first_row %>
      </ul>
    <% end %>
    
    <ul class="row">
    <% first_row = false %>
  <% end %>
  <li>
    <a class="project-link" href="<%= workspace_project_url(project.id) %>">
      <span class="title">
        <%= project.title %>
      </span>
      <iframe src="javascript:false;" scrolling="no" class="project-show" allowtransparency="true" data-project-id="<%= project.id %>">
      </iframe>
    </a>
  </li>
<% end %>
<% unless projects.empty? %>
  </ul>
<% end %>
</ul>

<script type="text/javascript">CodePal.Index.start()</script>

app/views/projects/_workspace.html.erb
<div class="workspace-container">
<div class="workspace">
  <div id="data" data-project-id="<%= params[:id] %>"></div>

  <%= render "editor", direction: "left", type: "html", options: ["html", "haml"], anim: 3 %>
  <%= render "editor", direction: "left", type: "css", options: ["css", "sass"], anim: 4 %>
  <%= render "editor", direction: "right", type: "js", options: ["javascript", "coffeescript"], anim: 5 %>

  <div class="divider">
    <div class="selections">
      <table border="0">
        <tr>
          <td>
            <button type="button">Submit</button>&nbsp;
          </td>
          <td nowrap>
            &nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" id="autorun" checked>Auto Submit?&nbsp;&nbsp;&nbsp;&nbsp;
          </td>
          <td nowrap>
            <a href="<%= project_url(params[:id]) %>" target="_blank">
              <button type="button">Open in new window</button>
            </a>
          </td>
        </td>
        <!--<form action="<%#= project_url(params[:id]) %>" method="get">
          <input type="submit" value="Open in new window">
        <form>-->
        <tr>
      </table>
    </div>
  </div>
  <div id="reloader">
    <iframe src="javascript:false;" name="code-render" scrolling="true">
    </iframe>
  </div>
</div>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1><br>
<%= render "form", edit: true, url: project_url(@project.id), button_text: "Save Changes" %>

app/views/projects/index.html.erb
<%= render "show_projects", projects: @projects %>

app/views/projects/new.html.erb
<h1 class="basic-header">Create a Project</h1>
<%= render "form", edit: false, url: projects_url, button_text: "Create Project" %>

app/views/projects/show.html.erb
<style><%= @project.css_file.first.body.html_safe %></style>
<%= @project.html_file.first.body.html_safe %>
<script><%= @project.js_file.first.body.html_safe %></script>

app/views/projects/workspace.html.erb
<div class="workspace">
  <div id="data" data-project-id="<%= params[:id] %>"></div>

  <%= render "editor", direction: "left", type: "html", options: ["html", "haml"] %>

  <%= render "editor", direction: "right", type: "css", options: ["css", "sass"] %>

  <div class="divider">
    <div class="selections">
      <button type="button">Submit</button>
      <input type="checkbox" id="autorun" checked>Auto Submit?
    </div>
  </div>

  <iframe src="javascript:false;" name="code-render" scrolling="true">
  </iframe>
</div>

<script>
  CodePal.Workspace.start(true);
</script>

app/views/projects/workspace_session.html.erb
<%= render "workspace" %>

<script>
  $(document).ready(function() {
    CodePal.Workspace.start(true, true);
  });
</script>