config/routes.rb
CodePal::Application.routes.draw do
  resources :users
  resources :projects do
    member do
      get 'workspace', to: 'projects#workspace', as: 'workspace' 
      get 'workspace/session', to: 'projects#workspace_session', as: 'workspace_session'
      
      get 'members/new', to: 'project_members#new', as: 'new_members'
      get 'members', to: 'project_members#index', as: 'members'
      post 'members', to: 'project_members#create', as: 'members'
      # resources :project_members, only: [:index, :new]
    end

    resources :users, only: [] do
      member do
        delete 'membership', to: 'project_members#destroy', as: 'members'
      end
    end
  end

  namespace :api do
    resources :projects, only: [:show] do
      resources :project_files, only: [:index] do
        collection do
          post 'save', to: 'project_files#save', as: 'save'
        end
      end
    end

    resources :user, only: [:show] do
      resources :projects, only: [:index]
    end
  end

  root to: 'projects#index'

  get '/login', to: 'session#new', as: 'login'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy', as: 'logout'
end

app/views/layouts/_navbar.html.erb
<nav>
  <ul class="left">
    <li>
      <a href="<%= root_url %>" title="Home Page">
        <%= image_tag "home.png" %>
      </a>
      <%#= button_to "Home", root_url, method: "get" %>
    </li>
    <li>
      <a href="<%= new_project_url %>" title="Create Project">
        <%= image_tag "new.png" %>
      </a>
      <%#= button_to "New Project", new_project_url, method: "get" %>
    </li>
    <% if logged_in? %>
      <li>
        <a href="<%= user_url(current_user.id) %>" title="My Projects">
          <%= image_tag "archive.png" %>
        </a>
        <%#= button_to "My Projects", user_url(current_user.id), method: "get" %>
      </li>
    <% end %>
  </ul> 
  <ul class="right">
  <% if logged_in? %>
      <li>
        <a href="<%= user_url(current_user.id) %>" title="My Page">
          <%= image_tag "info.png" %>
        </a>
        <%#= button_to current_user.username, user_url(current_user.id), method: "get" %>
      </li>
      <li>
        <a href="<%= logout_url %>" title="Logout">
          <%= image_tag "logout.png" %>
        </a>
        <%#= button_to "Logout", logout_url , method: "delete" %>
      </li>
  <% else %> 
      <li>
        <a href="<%= login_url %>" title="Login/Signup">
          <%= image_tag "key.png" %>
        </a>
        <%#= button_to "Login", login_url , method: "get" %>
      </li>
  <% end %>
  </ul>
</nav>

<script type="text/javascript">
$(document).ready(function() {
  $(document).tooltip();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html> <html>
<head>
  <title>CodePal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="off">
<div class="fadein scaleInv anim_1 container">
<div class="fadein scaleInv anim_2">
<%= render "layouts/navbar" %>
</div>

<% flash.each do |category| %>
  <% category.each do |message| %>
    <span class="flash-<%= category %>"><%= message %></span>
  <% end %>
<% end %>

<div class="alerts"></div>

<%= yield %>

</div>
</body>
</html>